In [28]:
#Reading CSV Files With csv

In [ ]:
import csv

In [27]:
with open('Customer_Data.txt') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            print(f'Column names are {", ".join(row)}')
            line_count += 1
        else:
            print(f'\t{row[0] + row[1]} {row[2]} is a {row[4]}, has IP Address {row[-2]} and lives at province {row[10]}.')
            line_count += 1
    print(f'Processed {line_count} lines.')

Column names are prefix, first, last, email, gender, age, company, profession, phone, postal, province, cc_no, cc_exp, cc_type, price(CAD), fav_color, ip, weekday
	Dr.Ray Morton is a Male, has IP Address 126.23.139.2 and lives at province MB.
	Miss.Claudia Rodriquez is a Female, has IP Address 106.198.76.211 and lives at province SK.
	Miss.Harry Meyer is a Female, has IP Address 186.150.187.29 and lives at province NS.
	Miss.Edith Gilbert is a Female, has IP Address 80.140.57.161 and lives at province YT.
	Dr.Lura Murphy is a Female, has IP Address 211.103.43.41 and lives at province ON.
	Mrs.Andre McGuire is a Male, has IP Address 44.6.228.222 and lives at province AB.
	Mr.Cody Thompson is a Female, has IP Address 46.87.230.156 and lives at province PE.
	Mr.Cory Duncan is a Male, has IP Address 209.5.235.14 and lives at province NU.
	Miss.Dorothy Watkins is a Female, has IP Address 11.57.253.20 and lives at province MB.
	Dr.Rose Tate is a Female, has IP Address 177.27.84.7 and lives at province NT.
Processed 11 lines.

In [ ]:
#Reading CSV Files Into a Dictionary With csv

In [34]:
with open('Customer_Data.txt', mode='r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            print(f'Column names are {", ".join(row)}')
            line_count += 1
        print(f'\t{row["first"]} {row["last"]} works for the {row["company"]}, as a {row["profession"]}.')
        line_count += 1
    print(f'Processed {line_count} lines.')

Column names are prefix, first, last, email, gender, age, company, profession, phone, postal, province, cc_no, cc_exp, cc_type, price(CAD), fav_color, ip, weekday
	Ray Morton works for the Medtronic Inc., as a Health Therapist.
	Claudia Rodriquez works for the Ames Department Stores, Inc., as a Health Therapist.
	Harry Meyer works for the CSX Corp., as a Political Scientist.
	Edith Gilbert works for the Murphy Oil Corporation, as a Transportation Manager.
	Lura Murphy works for the PETsMART Inc, as a Statistician.
	Andre McGuire works for the Timken Company, as a Communications Director.
	Cody Thompson works for the Nicor Inc, as a Special Education Teacher.
	Cory Duncan works for the Integrated Electrical Services Inc., as a Urban Planner.
	Dorothy Watkins works for the Service Corp. International, as a Veterinarian.
	Rose Tate works for the Eastman Kodak Company, as a Software Engineer.
Processed 11 lines.

In [35]:
import pandas as pd

In [64]:
df = pd.read_csv('Cust_Purch_Data.csv')
df.head()

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday
0,Dr.,Ray,Morton,sebvajom@kol.km,Male,38,Medtronic Inc.,Health Therapist,(987) 619-2695,B6V 3W3,MB,5.020000e+15,05/2018,Solo,8.36,Blue,126.23.139.2,Sunday
1,Miss,Claudia,Rodriquez,acu@jatsot.ug,Female,51,"Ames Department Stores, Inc.",Health Therapist,(356) 736-7352,G7M 5F3,SK,5.020000e+15,07/2028,Visa,68.31,Black,106.198.76.211,Tuesday
2,Miss,Harry,Meyer,zuz@lo.wf,Female,51,CSX Corp.,Political Scientist,(539) 246-1806,A0Z 6P9,NS,6.300000e+15,02/2023,Switch,34.65,Black,186.150.187.29,Wednesday
3,Miss,Edith,Gilbert,hansohsi@jupec.md,Female,55,Murphy Oil Corporation,Transportation Manager,(984) 962-7494,P9I 9H3,YT,3.530000e+15,02/2028,Maestro,64.59,White,80.140.57.161,Saturday
4,Dr.,Lura,Murphy,webediti@je.st,Female,20,PETsMART Inc,Statistician,(902) 568-9748,S1A 6K0,ON,4.030000e+15,10/2025,Diners Club International,20.83,Yellow,211.103.43.41,Friday

In [65]:
df["name"] = df["first"] + " " + df["last"]
df.head()

,prefix,first,last,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday,name
0,Dr.,Ray,Morton,sebvajom@kol.km,Male,38,Medtronic Inc.,Health Therapist,(987) 619-2695,B6V 3W3,MB,5.020000e+15,05/2018,Solo,8.36,Blue,126.23.139.2,Sunday,Ray Morton
1,Miss,Claudia,Rodriquez,acu@jatsot.ug,Female,51,"Ames Department Stores, Inc.",Health Therapist,(356) 736-7352,G7M 5F3,SK,5.020000e+15,07/2028,Visa,68.31,Black,106.198.76.211,Tuesday,Claudia Rodriquez
2,Miss,Harry,Meyer,zuz@lo.wf,Female,51,CSX Corp.,Political Scientist,(539) 246-1806,A0Z 6P9,NS,6.300000e+15,02/2023,Switch,34.65,Black,186.150.187.29,Wednesday,Harry Meyer
3,Miss,Edith,Gilbert,hansohsi@jupec.md,Female,55,Murphy Oil Corporation,Transportation Manager,(984) 962-7494,P9I 9H3,YT,3.530000e+15,02/2028,Maestro,64.59,White,80.140.57.161,Saturday,Edith Gilbert
4,Dr.,Lura,Murphy,webediti@je.st,Female,20,PETsMART Inc,Statistician,(902) 568-9748,S1A 6K0,ON,4.030000e+15,10/2025,Diners Club International,20.83,Yellow,211.103.43.41,Friday,Lura Murphy

In [69]:
df.columns

Index(['prefix', 'first', 'last', 'email', 'gender', 'age', 'company',
       'profession', 'phone', 'postal', 'province', 'cc_no', 'cc_exp',
       'cc_type', 'price(CAD)', 'fav_color', 'ip', 'weekday', 'name'],
      dtype='object')

In [78]:
df = df[['name','email', 'gender', 'age', 'company',
       'profession', 'phone', 'postal', 'province', 'cc_no', 'cc_exp',
       'cc_type', 'price(CAD)', 'fav_color', 'ip', 'weekday']]
df.head()

,name,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday
0,Ray Morton,sebvajom@kol.km,Male,38,Medtronic Inc.,Health Therapist,(987) 619-2695,B6V 3W3,MB,5.020000e+15,05/2018,Solo,8.36,Blue,126.23.139.2,Sunday
1,Claudia Rodriquez,acu@jatsot.ug,Female,51,"Ames Department Stores, Inc.",Health Therapist,(356) 736-7352,G7M 5F3,SK,5.020000e+15,07/2028,Visa,68.31,Black,106.198.76.211,Tuesday
2,Harry Meyer,zuz@lo.wf,Female,51,CSX Corp.,Political Scientist,(539) 246-1806,A0Z 6P9,NS,6.300000e+15,02/2023,Switch,34.65,Black,186.150.187.29,Wednesday
3,Edith Gilbert,hansohsi@jupec.md,Female,55,Murphy Oil Corporation,Transportation Manager,(984) 962-7494,P9I 9H3,YT,3.530000e+15,02/2028,Maestro,64.59,White,80.140.57.161,Saturday
4,Lura Murphy,webediti@je.st,Female,20,PETsMART Inc,Statistician,(902) 568-9748,S1A 6K0,ON,4.030000e+15,10/2025,Diners Club International,20.83,Yellow,211.103.43.41,Friday

In [79]:
parse_dates=['cc_exp']
df.head()

,name,email,gender,age,company,profession,phone,postal,province,cc_no,cc_exp,cc_type,price(CAD),fav_color,ip,weekday
0,Ray Morton,sebvajom@kol.km,Male,38,Medtronic Inc.,Health Therapist,(987) 619-2695,B6V 3W3,MB,5.020000e+15,05/2018,Solo,8.36,Blue,126.23.139.2,Sunday
1,Claudia Rodriquez,acu@jatsot.ug,Female,51,"Ames Department Stores, Inc.",Health Therapist,(356) 736-7352,G7M 5F3,SK,5.020000e+15,07/2028,Visa,68.31,Black,106.198.76.211,Tuesday
2,Harry Meyer,zuz@lo.wf,Female,51,CSX Corp.,Political Scientist,(539) 246-1806,A0Z 6P9,NS,6.300000e+15,02/2023,Switch,34.65,Black,186.150.187.29,Wednesday
3,Edith Gilbert,hansohsi@jupec.md,Female,55,Murphy Oil Corporation,Transportation Manager,(984) 962-7494,P9I 9H3,YT,3.530000e+15,02/2028,Maestro,64.59,White,80.140.57.161,Saturday
4,Lura Murphy,webediti@je.st,Female,20,PETsMART Inc,Statistician,(902) 568-9748,S1A 6K0,ON,4.030000e+15,10/2025,Diners Club International,20.83,Yellow,211.103.43.41,Friday

In [80]:
print(type(df['cc_exp'][0]))

<class 'str'>

In [82]:
df['cc_exp'] = pd.to_datetime(df['cc_exp'])
df['cc_exp'].dt.date
print(type(df['cc_exp'][0]))

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [83]:
import sys

In [85]:
print ("The script has the name %s" % (sys.argv[0]))

The script has the name C:\Users\Vadim\anaconda3\lib\site-packages\ipykernel_launcher.py

In [87]:
arguments = len(sys.argv) - 1
print ("The script is called with %i arguments" % (arguments))

The script is called with 2 arguments

In [88]:
position = 1
while (arguments >= position):
    print ("Parameter %i: %s" % (position, sys.argv[position]))
    position = position + 1

Parameter 1: -f
Parameter 2: C:\Users\Vadim\AppData\Roaming\jupyter\runtime\kernel-92967c21-ae5b-4ebc-84ad-415a8af6d2b4.json

In [90]:
# Include standard modules
import getopt

# Get full command-line arguments
full_cmd_arguments = sys.argv

# Keep all but the first
argument_list = full_cmd_arguments[1:]

print(argument_list)

['-f', 'C:\\Users\\Vadim\\AppData\\Roaming\\jupyter\\runtime\\kernel-92967c21-ae5b-4ebc-84ad-415a8af6d2b4.json']

In [91]:
short_options = "ho:v"
long_options = ["help", "output=", "verbose"]